name: Misspell Check

on:
  pull_request:
  push:
    branches: [main]

jobs:
  misspell:
    name: runner / misspell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: misspell
        uses: reviewdog/action-misspell@v1.13.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          level: warning
          locale: "US"
