name: Functional Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
      - name: Build Sif
        run: make
      - name: Run Sif with features
        run: |
          ./sif -u https://google.com -dnslist small -dirlist small -ports common -dork -git -whois -cms
          if [ $? -eq 0 ]; then
            echo "Sif ran successfully"
          else
            echo "Sif exited with an error"
            exit 1
          fi
